const REACT_QUESTIONS = [
  { _id: "react_1", question: "What hook is used to perform side effects in functional components?", options: [{text: "useState"}, {text: "useEffect"}, {text: "useContext"}, {text: "useReducer"}], correctOptionIndex: 1, difficulty: "Beginner", explanation: "useEffect is used for side effects." },
  { _id: "react_2", question: "What is the correct way to update state based on previous state?", options: [{text: "setCount(count + 1)"}, {text: "setCount(prev => prev + 1)"}, {text: "this.setState({count: count + 1})"}, {text: "state.count++"}], correctOptionIndex: 1, difficulty: "Intermediate", explanation: "Using the functional update form ensures you are working with the latest state." },
  { _id: "react_3", question: "Which method is called after a component is mounted?", options: [{text: "componentDidMount"}, {text: "componentDidUpdate"}, {text: "componentWillUnmount"}, {text: "render"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "componentDidMount is called after mounting." },
  { _id: "react_4", question: "What is the purpose of the 'key' prop in lists?", options: [{text: "To style the list items"}, {text: "To optimize reconciliation"}, {text: "To pass data to children"}, {text: "To define the list type"}], correctOptionIndex: 1, difficulty: "Intermediate", explanation: "Keys help React identify which items have changed, been added, or removed." },
  { _id: "react_5", question: "What is the 'Children' prop?", options: [{text: "A special prop that represents the content inside a component's tags"}, {text: "A prop that stores the child components' state"}, {text: "A method to pass data to parents"}, {text: "A way to define prop types"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "The 'children' prop is used to pass elements into components." },
  { _id: "react_6", question: "What is the difference between controlled and uncontrolled components?", options: [{text: "Controlled components have their state managed by React"}, {text: "Uncontrolled components have their state managed by React"}, {text: "Controlled components use refs to access values"}, {text: "There is no difference"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Controlled components have their value controlled by React state." },
  { _id: "react_7", question: "What is the purpose of React.memo?", options: [{text: "To cache component renders"}, {text: "To define prop types"}, {text: "To manage context"}, {text: "To handle routing"}], correctOptionIndex: 0, difficulty: "Advanced", explanation: "React.memo is a higher-order component that memoizes the rendered output." },
  { _id: "react_8", question: "How do you lift state up in React?", options: [{text: "By passing a setter function as a prop"}, {text: "By using the Context API"}, {text: "By using refs"}, {text: "By using Redux"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Lifting state up means moving state to a common ancestor and passing it down." },
  { _id: "react_9", question: "Which of the following is NOT a hook rule?", options: [{text: "Call hooks at the top level"}, {text: "Only call hooks from React functions"}, {text: "Call hooks inside loops"}, {text: "Call hooks conditionally (not allowed)"}], correctOptionIndex: 2, difficulty: "Intermediate", explanation: "You must not call hooks inside loops, conditions, or nested functions." },
  { _id: "react_10", question: "What is the Virtual DOM?", options: [{text: "A browser-native DOM representation"}, {text: "A lightweight copy of the real DOM"}, {text: "A server-side only DOM"}, {text: "A CSS-only DOM"}], correctOptionIndex: 1, difficulty: "Beginner", explanation: "The Virtual DOM is a lightweight copy of the real DOM used for performance optimizations." }
];

const NODE_QUESTIONS = [
  { _id: "node_1", question: "What does Node.js use for its event-driven architecture?", options: [{text: "EventEmitter"}, {text: "EventLoop"}, {text: "EventDispatcher"}, {text: "EventListener"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "The EventEmitter class is core to Node's event-driven architecture." },
  { _id: "node_2", question: "Which command starts a Node.js REPL?", options: [{text: "node start"}, {text: "node"}, {text: "node run"}, {text: "node repl"}], correctOptionIndex: 1, difficulty: "Beginner", explanation: "Running 'node' without arguments starts the REPL." },
  { _id: "node_3", question: "How do you export a module in Node.js?", options: [{text: "export default"}, {text: "module.exports"}, {text: "exports.module"}, {text: "export module"}], correctOptionIndex: 1, difficulty: "Beginner", explanation: "module.exports is the CommonJS way to export." },
  { _id: "node_4", question: "What is the purpose of the 'process' object?", options: [{text: "To manage the event loop"}, {text: "To provide info about the running Node process"}, {text: "To handle HTTP requests"}, {text: "To access the file system"}], correctOptionIndex: 1, difficulty: "Intermediate", explanation: "The process object provides information and control over the current Node.js process." },
  { _id: "node_5", question: "Which module is used for handling file paths?", options: [{text: "fs"}, {text: "path"}, {text: "url"}, {text: "os"}], correctOptionIndex: 1, difficulty: "Beginner", explanation: "The 'path' module provides utilities for working with file and directory paths." },
  { _id: "node_6", question: "What is a Buffer in Node.js?", options: [{text: "A stream handler"}, {text: "A way to handle binary data"}, {text: "A promise wrapper"}, {text: "An HTTP server"}], correctOptionIndex: 1, difficulty: "Intermediate", explanation: "Buffers are used to handle raw binary data in Node.js." },
  { _id: "node_7", question: "What is the main advantage of asynchronous I/O?", options: [{text: "Simpler code"}, {text: "Non-blocking execution"}, {text: "Faster CPU usage"}, {text: "Less memory usage"}], correctOptionIndex: 1, difficulty: "Beginner", explanation: "Asynchronous I/O allows Node.js to handle multiple requests without waiting for I/O operations to complete." },
  { _id: "node_8", question: "What is 'npm'?", options: [{text: "Node Package Manager"}, {text: "Node Process Manager"}, {text: "Node Program Module"}, {text: "Node Platform Manager"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "npm is the default package manager for Node.js." },
  { _id: "node_9", question: "How to handle errors in an asynchronous callback?", options: [{text: "Try-catch"}, {text: "Error-first callback pattern"}, {text: "Global error handler"}, {text: "Promise catch"}], correctOptionIndex: 1, difficulty: "Intermediate", explanation: "The error-first callback pattern is the traditional way to handle asynchronous errors." },
  { _id: "node_10", question: "Which Node.js module is used for web servers?", options: [{text: "http"}, {text: "web"}, {text: "server"}, {text: "request"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "The 'http' module allows Node.js to transfer data over HTTP." }
];

const MONGODB_QUESTIONS = [
  { _id: "mongo_1", question: "What is a document in MongoDB?", options: [{text: "A table row"}, {text: "A JSON-like object"}, {text: "A collection"}, {text: "A database file"}], correctOptionIndex: 1, difficulty: "Beginner", explanation: "MongoDB stores data in BSON documents." },
  { _id: "mongo_2", question: "Which command shows all collections?", options: [{text: "show db"}, {text: "show collections"}, {text: "list collections"}, {text: "db.list()"}], correctOptionIndex: 1, difficulty: "Beginner", explanation: "'show collections' lists the collections." },
  { _id: "mongo_3", question: "What is an index in MongoDB?", options: [{text: "A way to sort data"}, {text: "A data structure to improve query performance"}, {text: "A way to secure data"}, {text: "A backup method"}], correctOptionIndex: 1, difficulty: "Intermediate", explanation: "Indexes support the efficient execution of queries." },
  { _id: "mongo_4", question: "What is the aggregation framework?", options: [{text: "A way to insert data"}, {text: "A pipeline for data transformation"}, {text: "A way to delete data"}, {text: "A backup tool"}], correctOptionIndex: 1, difficulty: "Intermediate", explanation: "The aggregation framework processes documents to return computed results." },
  { _id: "mongo_5", question: "What is a 'sharded' cluster?", options: [{text: "A replica set"}, {text: "Data partitioned across multiple servers"}, {text: "A single server setup"}, {text: "A read-only database"}], correctOptionIndex: 1, difficulty: "Advanced", explanation: "Sharding distributes data across multiple machines." },
  { _id: "mongo_6", question: "How to perform a search with a condition?", options: [{text: "db.collection.find({condition})"}, {text: "db.collection.search({condition})"}, {text: "db.collection.query({condition})"}, {text: "db.collection.get({condition})"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "find() is used to query data." },
  { _id: "mongo_7", question: "What is the purpose of $lookup?", options: [{text: "To update data"}, {text: "To perform a left outer join"}, {text: "To delete data"}, {text: "To add a new document"}], correctOptionIndex: 1, difficulty: "Advanced", explanation: "$lookup performs a join in the aggregation pipeline." },
  { _id: "mongo_8", question: "What is a replica set?", options: [{text: "A sharded cluster"}, {text: "A group of nodes with the same data for high availability"}, {text: "A single server"}, {text: "A read-only copy"}], correctOptionIndex: 1, difficulty: "Intermediate", explanation: "Replica sets provide redundancy and high availability." },
  { _id: "mongo_9", question: "How do you insert a single document?", options: [{text: "insertOne()"}, {text: "insert()"}, {text: "addOne()"}, {text: "save()"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "insertOne() is the standard method for inserting one document." },
  { _id: "mongo_10", question: "What is BSON?", options: [{text: "Binary JSON"}, {text: "Basic JSON"}, {text: "Best JSON"}, {text: "Binary Serialization Object Notation"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "BSON is the binary-encoded serialization of JSON documents." }
];

const TYPESCRIPT_QUESTIONS = [
  { _id: "ts_1", question: "What is the file extension for TypeScript files?", options: [{text: ".ts"}, {text: ".js"}, {text: ".tst"}, {text: ".typescript"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: ".ts is the extension." },
  { _id: "ts_2", question: "What is an interface?", options: [{text: "A runtime class"}, {text: "A structure to define type contracts"}, {text: "A way to import modules"}, {text: "A type of variable"}], correctOptionIndex: 1, difficulty: "Intermediate", explanation: "Interfaces define structure." },
  { _id: "ts_3", question: "What is a generic?", options: [{text: "A flexible type"}, {text: "A base class"}, {text: "An interface"}, {text: "A function"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Generics allow for type reuse." },
  { _id: "ts_4", question: "What does 'any' type do?", options: [{text: "Disables type checking for a variable"}, {text: "Ensures type safety"}, {text: "Makes a variable read-only"}, {text: "Defines a union type"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "'any' opts out of type checking." },
  { _id: "ts_5", question: "What is a union type?", options: [{text: "A type that can be one of several types"}, {text: "A combination of types"}, {text: "A type alias"}, {text: "A class extension"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Union types (A | B) allow multiple possible types." },
  { _id: "ts_6", question: "What is a type alias?", options: [{text: "A name for a type"}, {text: "A variable"}, {text: "An interface"}, {text: "A class"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "Type aliases (type T = ...) give names to types." },
  { _id: "ts_7", question: "What are decorators?", options: [{text: "A way to annotate classes/methods"}, {text: "A style feature"}, {text: "A module loader"}, {text: "A type constraint"}], correctOptionIndex: 0, difficulty: "Advanced", explanation: "Decorators provide a way to add annotations and metadata to classes and members." },
  { _id: "ts_8", question: "What is 'never' type?", options: [{text: "A type that never occurs"}, {text: "A null type"}, {text: "An undefined type"}, {text: "An any type"}], correctOptionIndex: 0, difficulty: "Advanced", explanation: "'never' represents values that never occur." },
  { _id: "ts_9", question: "How to define an optional property in an interface?", options: [{text: "prop?: type"}, {text: "prop: type?"}, {text: "prop: type = null"}, {text: "prop: type|undefined"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "The '?' marks a property as optional." },
  { _id: "ts_10", question: "What is a mapped type?", options: [{text: "A type based on another type's keys"}, {text: "A type alias"}, {text: "A generic interface"}, {text: "A union type"}], correctOptionIndex: 0, difficulty: "Advanced", explanation: "Mapped types allow creating new types from existing types by mapping their keys." }
];

const JS_QUESTIONS = [
  { _id: "js_1", question: "Which keyword defines a block-scoped variable?", options: [{text: "var"}, {text: "let"}, {text: "const"}, {text: "define"}], correctOptionIndex: 1, difficulty: "Beginner", explanation: "let is block-scoped." },
  { _id: "js_2", question: "What is a closure?", options: [{text: "A function that returns a function"}, {text: "A function that has access to its lexical scope"}, {text: "A private variable"}, {text: "A global function"}], correctOptionIndex: 1, difficulty: "Intermediate", explanation: "Closures preserve the lexical scope." },
  { _id: "js_3", question: "Which method adds an element to the end of an array?", options: [{text: "push()"}, {text: "pop()"}, {text: "shift()"}, {text: "unshift()"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "push() adds to the end." },
  { _id: "js_4", question: "What is the result of '1' + 2?", options: [{text: "3"}, {text: "'12'"}, {text: "undefined"}, {text: "error"}], correctOptionIndex: 1, difficulty: "Beginner", explanation: "JavaScript performs type coercion." },
  { _id: "js_5", question: "What does '===' check?", options: [{text: "Value equality"}, {text: "Value and type equality"}, {text: "Reference equality"}, {text: "Assignment"}], correctOptionIndex: 1, difficulty: "Beginner", explanation: "=== checks value and type." },
  { _id: "js_6", question: "What is 'this' keyword?", options: [{text: "The global object"}, {text: "The current execution context"}, {text: "The function"}, {text: "The parent object"}], correctOptionIndex: 1, difficulty: "Intermediate", explanation: "'this' refers to the object in the current context." },
  { _id: "js_7", question: "What is a Promise?", options: [{text: "An async operation wrapper"}, {text: "A synchronous function"}, {text: "A value"}, {text: "An error handler"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Promises handle asynchronous operations." },
  { _id: "js_8", question: "How to define a class?", options: [{text: "function class()"}, {text: "class Name {}"}, {text: "define class Name"}, {text: "let Name = {}"}], correctOptionIndex: 1, difficulty: "Beginner", explanation: "class is used." },
  { _id: "js_9", question: "What is an arrow function?", options: [{text: "A short function syntax"}, {text: "A function with no 'this' binding"}, {text: "Both of the above"}, {text: "None of the above"}], correctOptionIndex: 2, difficulty: "Intermediate", explanation: "Arrow functions have short syntax and lexical 'this'." },
  { _id: "js_10", question: "What is a generator function?", options: [{text: "A function that can pause execution"}, {text: "A function that generates objects"}, {text: "A function that generates CSS"}, {text: "A class"}], correctOptionIndex: 0, difficulty: "Advanced", explanation: "Generators use 'function*' and 'yield' to pause." }
];

const CSS_QUESTIONS = [
  { _id: "css_1", question: "What does CSS stand for?", options: [{text: "Colorful Style Sheets"}, {text: "Cascading Style Sheets"}, {text: "Computer Style Sheets"}, {text: "Creative Style Sheets"}], correctOptionIndex: 1, difficulty: "Beginner", explanation: "Cascading Style Sheets." },
  { _id: "css_2", question: "Which property is for changing font size?", options: [{text: "text-size"}, {text: "font-size"}, {text: "size"}, {text: "font-style"}], correctOptionIndex: 1, difficulty: "Beginner", explanation: "font-size." },
  { _id: "css_3", question: "What is a flexbox?", options: [{text: "A layout module"}, {text: "A box type"}, {text: "A CSS property"}, {text: "An animation"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Flexbox is a layout module." },
  { _id: "css_4", question: "What does 'display: none' do?", options: [{text: "Hides element and removes from flow"}, {text: "Hides element but keeps space"}, {text: "Changes element to inline"}, {text: "Changes element to block"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "Removes from layout." },
  { _id: "css_5", question: "Which position property keeps element in the same place when scrolling?", options: [{text: "relative"}, {text: "absolute"}, {text: "fixed"}, {text: "static"}], correctOptionIndex: 2, difficulty: "Intermediate", explanation: "Fixed positions relative to the viewport." },
  { _id: "css_6", question: "What is a media query used for?", options: [{text: "Responsiveness"}, {text: "Animations"}, {text: "Colors"}, {text: "Typography"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Media queries enable responsive designs." },
  { _id: "css_7", question: "What is a CSS pseudo-class?", options: [{text: "A selector for specific states"}, {text: "An element"}, {text: "A property"}, {text: "A variable"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Pseudo-classes like :hover define element states." },
  { _id: "css_8", question: "Which property changes the space inside a box?", options: [{text: "margin"}, {text: "padding"}, {text: "border"}, {text: "width"}], correctOptionIndex: 1, difficulty: "Beginner", explanation: "Padding is internal spacing." },
  { _id: "css_9", question: "What is CSS grid?", options: [{text: "A 2D layout system"}, {text: "A 1D layout system"}, {text: "A color palette"}, {text: "An animation"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Grid is a 2D layout system." },
  { _id: "css_10", question: "What is the Box Model?", options: [{text: "Margin, Border, Padding, Content"}, {text: "Content, Padding, Border, Margin"}, {text: "Border, Margin, Content, Padding"}, {text: "None of the above"}], correctOptionIndex: 1, difficulty: "Intermediate", explanation: "Content + Padding + Border + Margin = Box Model." }
];

const NEXTJS_QUESTIONS = [
  { _id: "next_1", question: "What is a key benefit of Next.js?", options: [{text: "SSR/SSG support"}, {text: "Easy CSS"}, {text: "No JavaScript"}, {text: "Only client-side"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "SSR and SSG are core Next.js features." },
  { _id: "next_2", question: "What is the App Router?", options: [{text: "The routing system in newer Next.js versions"}, {text: "A database"}, {text: "A CSS file"}, {text: "A plugin"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "The App Router uses React Server Components." },
  { _id: "next_3", question: "What is getServerSideProps?", options: [{text: "SSR data fetching"}, {text: "SSG data fetching"}, {text: "Client-side data fetching"}, {text: "An API route"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "SSR fetching." },
  { _id: "next_4", question: "What is Incremental Static Regeneration (ISR)?", options: [{text: "Static pages update without rebuilding the site"}, {text: "Dynamic rendering"}, {text: "Client-side rendering"}, {text: "CSS rendering"}], correctOptionIndex: 0, difficulty: "Advanced", explanation: "Updates static pages in the background." },
  { _id: "next_5", question: "What are Server Components?", options: [{text: "Components that run only on the server"}, {text: "Components that run only on the client"}, {text: "Components that run on both"}, {text: "None of the above"}], correctOptionIndex: 0, difficulty: "Advanced", explanation: "Server Components are rendered on the server." },
  { _id: "next_6", question: "What is an API route?", options: [{text: "Serverless functions within Next.js"}, {text: "A routing type"}, {text: "A CSS feature"}, {text: "An HTML element"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "API routes allow server-side logic." },
  { _id: "next_7", question: "How to optimize images in Next.js?", options: [{text: "Next/Image component"}, {text: "<img> tag"}, {text: "CSS"}, {text: "Canvas"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "The Image component handles optimization." },
  { _id: "next_8", question: "What is the purpose of _app.js?", options: [{text: "To customize the initial page load"}, {text: "To define layout"}, {text: "To manage global CSS"}, {text: "All of the above"}], correctOptionIndex: 3, difficulty: "Intermediate", explanation: "Used for layout and global state/CSS." },
  { _id: "next_9", question: "What is dynamic routing?", options: [{text: "Using [param] in file names"}, {text: "Using routing tables"}, {text: "Using CSS"}, {text: "Using JS objects"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Bracket syntax defines dynamic params." },
  { _id: "next_10", question: "What is middleware?", options: [{text: "Code that runs before a request completes"}, {text: "A React component"}, {text: "An API route"}, {text: "A database query"}], correctOptionIndex: 0, difficulty: "Advanced", explanation: "Middleware intercepts requests." }
];

const PYTHON_QUESTIONS = [
  { _id: "py_1", question: "How to define a function?", options: [{text: "def func():"}, {text: "function func():"}, {text: "func() = {}"}, {text: "let func = {}"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "def is used." },
  { _id: "py_2", question: "Which is a list?", options: [{text: "{1,2}"}, {text: "[1,2]"}, {text: "(1,2)"}, {text: "1:2"}], correctOptionIndex: 1, difficulty: "Beginner", explanation: "[] defines a list." },
  { _id: "py_3", question: "What is a dictionary?", options: [{text: "Key-value store"}, {text: "Ordered list"}, {text: "A set"}, {text: "An array"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "Dictionaries store key-value pairs." },
  { _id: "py_4", question: "How to import a module?", options: [{text: "require()"}, {text: "import"}, {text: "include"}, {text: "load()"}], correctOptionIndex: 1, difficulty: "Beginner", explanation: "import keyword." },
  { _id: "py_5", question: "What is a list comprehension?", options: [{text: "A way to create lists concisely"}, {text: "A list sort method"}, {text: "A list deletion method"}, {text: "An error"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Compact list creation." },
  { _id: "py_6", question: "What is a generator?", options: [{text: "A function that yields values"}, {text: "A function that returns a list"}, {text: "A class"}, {text: "An object"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Generators use yield." },
  { _id: "py_7", question: "What is a decorator?", options: [{text: "A function that modifies another function"}, {text: "A class"}, {text: "A variable"}, {text: "A type"}], correctOptionIndex: 0, difficulty: "Advanced", explanation: "Decorators use @ syntax." },
  { _id: "py_8", question: "Which of these is immutable?", options: [{text: "list"}, {text: "dict"}, {text: "tuple"}, {text: "set"}], correctOptionIndex: 2, difficulty: "Beginner", explanation: "Tuples cannot be changed." },
  { _id: "py_9", question: "What is pip?", options: [{text: "Package manager"}, {text: "Code runner"}, {text: "IDE"}, {text: "Compiler"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "pip installs packages." },
  { _id: "py_10", question: "What is PEP 8?", options: [{text: "Style guide"}, {text: "Language spec"}, {text: "Compiler"}, {text: "Library"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "Style guide for Python code." }
];

const JAVA_QUESTIONS = [
  { _id: "java_1", question: "What is a class?", options: [{text: "A blueprint for objects"}, {text: "A variable"}, {text: "A method"}, {text: "A library"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "Classes define objects." },
  { _id: "java_2", question: "Which keyword creates an object?", options: [{text: "new"}, {text: "create"}, {text: "instance"}, {text: "make"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "new creates instances." },
  { _id: "java_3", question: "What is inheritance?", options: [{text: "A class acquiring properties of another"}, {text: "A function"}, {text: "A type"}, {text: "An error"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Child inherits from parent." },
  { _id: "java_4", question: "What is polymorphism?", options: [{text: "Many forms"}, {text: "One form"}, {text: "No form"}, {text: "A variable"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Polymorphism means many forms." },
  { _id: "java_5", question: "What is an interface?", options: [{text: "A contract"}, {text: "A class"}, {text: "A variable"}, {text: "A method"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Interfaces define methods to implement." },
  { _id: "java_6", question: "Which is not a primitive type?", options: [{text: "int"}, {text: "String"}, {text: "boolean"}, {text: "double"}], correctOptionIndex: 1, difficulty: "Beginner", explanation: "String is an object." },
  { _id: "java_7", question: "What is the main method signature?", options: [{text: "public static void main(String[] args)"}, {text: "main()"}, {text: "void main()"}, {text: "static void main()"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "Standard entry point." },
  { _id: "java_8", question: "What is exception handling?", options: [{text: "Try-catch blocks"}, {text: "If-else"}, {text: "Looping"}, {text: "Variables"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Manages runtime errors." },
  { _id: "java_9", question: "What is a package?", options: [{text: "Namespace for classes"}, {text: "A library"}, {text: "A variable"}, {text: "A method"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "Packages organize classes." },
  { _id: "java_10", question: "What is a constructor?", options: [{text: "Method for initialization"}, {text: "Method for destruction"}, {text: "Variable"}, {text: "Class"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "Initializes objects." }
];

const DOCKER_QUESTIONS = [
  { _id: "docker_1", question: "What is a Docker image?", options: [{text: "Blueprint for containers"}, {text: "A running container"}, {text: "A network"}, {text: "A volume"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "Images are read-only templates." },
  { _id: "docker_2", question: "What is a Docker container?", options: [{text: "A running instance of an image"}, {text: "An image"}, {text: "A registry"}, {text: "A network"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "Containers run applications." },
  { _id: "docker_3", question: "What is a Dockerfile?", options: [{text: "Script to build images"}, {text: "Image"}, {text: "Container"}, {text: "Config file"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "Instructions for building." },
  { _id: "docker_4", question: "What is Docker Compose?", options: [{text: "Multi-container tool"}, {text: "Single container tool"}, {text: "Image tool"}, {text: "Registry tool"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Orchestrates services." },
  { _id: "docker_5", question: "What is a Docker registry?", options: [{text: "Store for images"}, {text: "Store for containers"}, {text: "Network"}, {text: "Volume"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "Like Docker Hub." },
  { _id: "docker_6", question: "What is a volume?", options: [{text: "Persistent storage"}, {text: "Memory"}, {text: "CPU"}, {text: "Image"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Persists data." },
  { _id: "docker_7", question: "How to stop a container?", options: [{text: "docker stop"}, {text: "docker kill"}, {text: "docker pause"}, {text: "docker remove"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "Stop signals container." },
  { _id: "docker_8", question: "What is a bridge network?", options: [{text: "Default network type"}, {text: "Host network"}, {text: "Overlay network"}, {text: "None"}], correctOptionIndex: 0, difficulty: "Advanced", explanation: "Connects containers on same host." },
  { _id: "docker_9", question: "What is docker build?", options: [{text: "Command to create image"}, {text: "Command to run container"}, {text: "Command to pull image"}, {text: "Command to push image"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "Creates images." },
  { _id: "docker_10", question: "What is the purpose of EXPOSE?", options: [{text: "Documenting ports"}, {text: "Opening ports"}, {text: "Volume mapping"}, {text: "Setting environment"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Informs which port to listen." }
];

const K8S_QUESTIONS = [
  { _id: "k8s_1", question: "What is a pod?", options: [{text: "Smallest unit in K8s"}, {text: "Cluster node"}, {text: "Database"}, {text: "Container"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "Atomic unit." },
  { _id: "k8s_2", question: "What is a deployment?", options: [{text: "Defines pod lifecycle"}, {text: "A node"}, {text: "A service"}, {text: "A volume"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Manages pods." },
  { _id: "k8s_3", question: "What is a service?", options: [{text: "Exposes pods"}, {text: "Manages pods"}, {text: "A node"}, {text: "Volume"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Stable network endpoint." },
  { _id: "k8s_4", question: "What is kubectl?", options: [{text: "CLI tool"}, {text: "K8s API"}, {text: "Database"}, {text: "Node type"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "Used to manage K8s." },
  { _id: "k8s_5", question: "What is a node?", options: [{text: "Worker machine"}, {text: "Pod"}, {text: "Service"}, {text: "Deployment"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Physical/VM machine." },
  { _id: "k8s_6", question: "What is ingress?", options: [{text: "Exposes routes"}, {text: "Service"}, {text: "Pod"}, {text: "Node"}], correctOptionIndex: 0, difficulty: "Advanced", explanation: "Manages HTTP traffic." },
  { _id: "k8s_7", question: "What is configmap?", options: [{text: "Store configuration"}, {text: "Store secrets"}, {text: "Store data"}, {text: "Store pods"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Config data storage." },
  { _id: "k8s_8", question: "What are secrets?", options: [{text: "Encrypted config"}, {text: "Config map"}, {text: "Pod"}, {text: "Node"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Sensitive data." },
  { _id: "k8s_9", question: "What is a cluster?", options: [{text: "Set of nodes"}, {text: "A pod"}, {text: "A service"}, {text: "A deployment"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "Group of nodes." },
  { _id: "k8s_10", question: "What is namespace?", options: [{text: "Logical isolation"}, {text: "A node"}, {text: "A pod"}, {text: "A service"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Isolates resources." }
];

const GRAPHQL_QUESTIONS = [
  { _id: "gql_1", question: "What is GraphQL?", options: [{text: "Query language"}, {text: "Database"}, {text: "Library"}, {text: "Framework"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "Query language." },
  { _id: "gql_2", question: "What is a resolver?", options: [{text: "Function to fetch data"}, {text: "Schema"}, {text: "Type"}, {text: "Query"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Resolvers provide data." },
  { _id: "gql_3", question: "What is a schema?", options: [{text: "Defines types"}, {text: "Database query"}, {text: "CSS"}, {text: "HTML"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Type definitions." },
  { _id: "gql_4", question: "What is a mutation?", options: [{text: "Write operation"}, {text: "Read operation"}, {text: "CSS rule"}, {text: "Variable"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Modifies data." },
  { _id: "gql_5", question: "What is a query?", options: [{text: "Read operation"}, {text: "Write operation"}, {text: "CSS rule"}, {text: "Variable"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Fetches data." },
  { _id: "gql_6", question: "What is a fragment?", options: [{text: "Reusable selection"}, {text: "Schema"}, {text: "Resolver"}, {text: "Type"}], correctOptionIndex: 0, difficulty: "Advanced", explanation: "Reuse fields." },
  { _id: "gql_7", question: "What is subscription?", options: [{text: "Real-time updates"}, {text: "Query"}, {text: "Mutation"}, {text: "Schema"}], correctOptionIndex: 0, difficulty: "Advanced", explanation: "Real-time data." },
  { _id: "gql_8", question: "What is an input type?", options: [{text: "Type for mutations"}, {text: "Type for queries"}, {text: "Type for resolver"}, {text: "Type for CSS"}], correctOptionIndex: 0, difficulty: "Advanced", explanation: "Structured input." },
  { _id: "gql_9", question: "What is Apollo?", options: [{text: "GraphQL client/server"}, {text: "Database"}, {text: "Library"}, {text: "Framework"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Popular GraphQL toolset." },
  { _id: "gql_10", question: "What is an enum type?", options: [{text: "Set of allowed values"}, {text: "Variable"}, {text: "Class"}, {text: "Method"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Enumerated values." }
];

const REST_QUESTIONS = [
  { _id: "rest_1", question: "What is REST?", options: [{text: "Architectural style"}, {text: "Database"}, {text: "Language"}, {text: "Framework"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "REST is architectural." },
  { _id: "rest_2", question: "Which method is for reading?", options: [{text: "GET"}, {text: "POST"}, {text: "PUT"}, {text: "DELETE"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "GET fetches." },
  { _id: "rest_3", question: "Which method is for creating?", options: [{text: "POST"}, {text: "GET"}, {text: "PUT"}, {text: "DELETE"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "POST creates." },
  { _id: "rest_4", question: "Which method is for updating?", options: [{text: "PUT/PATCH"}, {text: "POST"}, {text: "GET"}, {text: "DELETE"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "PUT updates." },
  { _id: "rest_5", question: "Which method is for deleting?", options: [{text: "DELETE"}, {text: "GET"}, {text: "POST"}, {text: "PUT"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "DELETE removes." },
  { _id: "rest_6", question: "What is a resource?", options: [{text: "An entity/object"}, {text: "A method"}, {text: "A status code"}, {text: "A URL"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "REST entities." },
  { _id: "rest_7", question: "What is stateless?", options: [{text: "Server doesn't store state"}, {text: "Client stores state"}, {text: "Database"}, {text: "Cache"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Statelessness." },
  { _id: "rest_8", question: "What is HATEOAS?", options: [{text: "Hypermedia as engine"}, {text: "Database"}, {text: "Protocol"}, {text: "CSS"}], correctOptionIndex: 0, difficulty: "Advanced", explanation: "Hypermedia." },
  { _id: "rest_9", question: "What is a status code?", options: [{text: "Response status"}, {text: "URL"}, {text: "Header"}, {text: "Body"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "Response indicator." },
  { _id: "rest_10", question: "What is an endpoint?", options: [{text: "URL for a resource"}, {text: "Database"}, {text: "CSS"}, {text: "Method"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "Access point." }
];

const POSTGRES_QUESTIONS = [
  { _id: "pg_1", question: "What is PostgreSQL?", options: [{text: "Relational DB"}, {text: "NoSQL DB"}, {text: "Cache"}, {text: "Framework"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "Relational DB." },
  { _id: "pg_2", question: "What is SQL?", options: [{text: "Query language"}, {text: "Database"}, {text: "Library"}, {text: "Framework"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "Query language." },
  { _id: "pg_3", question: "What is a table?", options: [{text: "Data structure"}, {text: "Query"}, {text: "Schema"}, {text: "View"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "Data container." },
  { _id: "pg_4", question: "What is a primary key?", options: [{text: "Unique identifier"}, {text: "Foreign key"}, {text: "Index"}, {text: "Constraint"}], correctOptionIndex: 0, difficulty: "Beginner", explanation: "Unique row ID." },
  { _id: "pg_5", question: "What is a foreign key?", options: [{text: "Link to other table"}, {text: "Primary key"}, {text: "Index"}, {text: "Constraint"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Connects tables." },
  { _id: "pg_6", question: "What is a join?", options: [{text: "Combining tables"}, {text: "Querying"}, {text: "Indexing"}, {text: "Constraint"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Combines data." },
  { _id: "pg_7", question: "What is a view?", options: [{text: "Virtual table"}, {text: "Real table"}, {text: "Index"}, {text: "Constraint"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Stored query." },
  { _id: "pg_8", question: "What is a transaction?", options: [{text: "Atomic operation"}, {text: "Query"}, {text: "Index"}, {text: "Table"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "ACID property." },
  { _id: "pg_9", question: "What is an index?", options: [{text: "Performance tool"}, {text: "Constraint"}, {text: "Join"}, {text: "Table"}], correctOptionIndex: 0, difficulty: "Intermediate", explanation: "Speeds up queries." },
  { _id: "pg_10", question: "What is a trigger?", options: [{text: "Automated event"}, {text: "Constraint"}, {text: "Join"}, {text: "Index"}], correctOptionIndex: 0, difficulty: "Advanced", explanation: "Runs on events." }
];
