const mongoose = require('mongoose');
const Question = require('../models/Question');
const connectDB = require('../config/database');

// NOTE: Appending 40 new questions (20 JS, 20 TS) to the pool.

const techData = [
  // --- JAVASCRIPT (20) ---
  { technology: 'JavaScript', category: 'Language', difficulty: 'hard', question: 'How does JavaScript handle asynchronous operations under the hood?', options: [{ text: 'Multi-threading', isCorrect: false }, { text: 'Event loop with callback queue and microtask queue', isCorrect: true }, { text: 'Blocking', isCorrect: false }, { text: 'API', isCorrect: false }], explanation: 'Event loop with callback/microtask queue.', points: 20 },
  { technology: 'JavaScript', category: 'Language', difficulty: 'hard', question: 'What is the difference between microtasks and macrotasks in JavaScript?', options: [{ text: 'Same', isCorrect: false }, { text: 'Microtasks (Promises) execute before macrotasks (setTimeout)', isCorrect: true }, { text: 'Macrotasks faster', isCorrect: false }, { text: 'No order', isCorrect: false }], explanation: 'Microtasks execute before macrotasks.', points: 20 },
  {
    technology: 'JavaScript', category: 'Language', difficulty: 'hard', question: 'What will be the output of: console.log(1); setTimeout(() => console.log(2), 0); Promise
      .resolve().then(() => console.log(3)); console.log(4); ', options: [{ text: '1 2 3 4', isCorrect: false }, { text: '1 4 2 3', isCorrect: false }, { text: '1 4 3 2', isCorrect: true }, { text: '4 1 3 2', isCorrect: false }], explanation: '1, 4, then promises, then setTimeouts.', points: 20 },
  { technology: 'JavaScript', category: 'Language', difficulty: 'medium', question: 'What is closure in JavaScript?', options: [{ text: 'Function error', isCorrect: false }, { text: 'Function retaining access to its lexical scope', isCorrect: true }, { text: 'Loop', isCorrect: false }, { text: 'API', isCorrect: false }], explanation: 'Retains lexical scope access.', points: 15 },
  { technology: 'JavaScript', category: 'Language', difficulty: 'medium', question: 'What is the difference between == and ===?', options: [{ text: 'Same', isCorrect: false }, { text: '=== checks type + value, == does coercion', isCorrect: true }, { text: '== strict', isCorrect: false }, { text: 'None', isCorrect: false }], explanation: 'Strict equality vs coercion.', points: 15 },
  { technology: 'JavaScript', category: 'Language', difficulty: 'medium', question: 'What is hoisting in JavaScript?', options: [{ text: 'Execution', isCorrect: false }, { text: 'Moving declarations to top of scope during compilation', isCorrect: true }, { text: 'API', isCorrect: false }, { text: 'Loop', isCorrect: false }], explanation: 'Declarations moved to scope top.', points: 15 },
  { technology: 'JavaScript', category: 'Language', difficulty: 'hard', question: 'What is the temporal dead zone?', options: [{ text: 'Error', isCorrect: false }, { text: 'Time before variable initialization where access throws error (let/const)', isCorrect: true }, { text: 'Loop', isCorrect: false }, { text: 'API', isCorrect: false }], explanation: 'Accessing let/const before initialization.', points: 20 },
  { technology: 'JavaScript', category: 'Language', difficulty: 'hard', question: 'What is prototypal inheritance?', options: [{ text: 'Class-based', isCorrect: false }, { text: 'Objects inherit from other objects via prototype chain', isCorrect: true }, { text: 'API', isCorrect: false }, { text: 'Loop', isCorrect: false }], explanation: 'Inheritance via prototype chain.', points: 20 },
  { technology: 'JavaScript', category: 'Language', difficulty: 'medium', question: 'What does this refer to in JavaScript?', options: [{ text: 'Global always', isCorrect: false }, { text: 'Depends on calling context', isCorrect: true }, { text: 'Function', isCorrect: false }, { text: 'API', isCorrect: false }], explanation: 'Depends on calling context.', points: 15 },
  { technology: 'JavaScript', category: 'Language', difficulty: 'hard', question: 'What is currying?', options: [{ text: 'Loop', isCorrect: false }, { text: 'Transform function into sequence of functions each taking one argument', isCorrect: true }, { text: 'API', isCorrect: false }, { text: 'Error', isCorrect: false }], explanation: 'Function transformation into multi-arity.', points: 20 },
  { technology: 'JavaScript', category: 'Language', difficulty: 'hard', question: 'What is debouncing?', options: [{ text: 'Loop', isCorrect: false }, { text: 'Limit function execution after delay of inactivity', isCorrect: true }, { text: 'API', isCorrect: false }, { text: 'Error', isCorrect: false }], explanation: 'Limits execution after inactivity.', points: 20 },
  { technology: 'JavaScript', category: 'Language', difficulty: 'hard', question: 'What is throttling?', options: [{ text: 'Loop', isCorrect: false }, { text: 'Limit function execution rate over time', isCorrect: true }, { text: 'API', isCorrect: false }, { text: 'Error', isCorrect: false }], explanation: 'Limits rate of execution.', points: 20 },
  { technology: 'JavaScript', category: 'Language', difficulty: 'medium', question: 'What is immutability in JavaScript?', options: [{ text: 'Changeable', isCorrect: false }, { text: 'Data that cannot be modified after creation', isCorrect: true }, { text: 'API', isCorrect: false }, { text: 'Loop', isCorrect: false }], explanation: 'Data cannot be modified.', points: 15 },
  { technology: 'JavaScript', category: 'Language', difficulty: 'medium', question: 'What is event delegation?', options: [{ text: 'Loop', isCorrect: false }, { text: 'Handling events at parent level using bubbling', isCorrect: true }, { text: 'API', isCorrect: false }, { text: 'Error', isCorrect: false }], explanation: 'Handling events at parent level.', points: 15 },
  { technology: 'JavaScript', category: 'Language', difficulty: 'medium', question: 'What is Promise chaining?', options: [{ text: 'Loop', isCorrect: false }, { text: 'Executing async operations sequentially using .then()', isCorrect: true }, { text: 'API', isCorrect: false }, { text: 'Error', isCorrect: false }], explanation: 'Sequential async execution.', points: 15 },
  { technology: 'JavaScript', category: 'Language', difficulty: 'hard', question: 'What is the difference between shallow and deep copy?', options: [{ text: 'Same', isCorrect: false }, { text: 'Shallow copies references; deep copies values recursively', isCorrect: true }, { text: 'Deep faster', isCorrect: false }, { text: 'None', isCorrect: false }], explanation: 'Reference vs recursive value copy.', points: 20 },
  { technology: 'JavaScript', category: 'Language', difficulty: 'medium', question: 'What is a pure function?', options: [{ text: 'API', isCorrect: false }, { text: 'Same input → same output, no side effects', isCorrect: true }, { text: 'Loop', isCorrect: false }, { text: 'Error', isCorrect: false }], explanation: 'Consistent output, no side effects.', points: 15 },
  { technology: 'JavaScript', category: 'Language', difficulty: 'hard', question: 'What is memory leak in JavaScript?', options: [{ text: 'API', isCorrect: false }, { text: 'Unused memory not released by garbage collector', isCorrect: true }, { text: 'Loop', isCorrect: false }, { text: 'Error', isCorrect: false }], explanation: 'Failure of garbage collector.', points: 20 },
  { technology: 'JavaScript', category: 'Language', difficulty: 'medium', question: 'What is the purpose of bind() method?', options: [{ text: 'Loop', isCorrect: false }, { text: 'Set this context explicitly', isCorrect: true }, { text: 'API', isCorrect: false }, { text: 'Error', isCorrect: false }], explanation: 'Sets this context.', points: 15 },
  { technology: 'JavaScript', category: 'Language', difficulty: 'hard', question: 'What is the difference between call() and apply()?', options: [{ text: 'Same', isCorrect: false }, { text: 'call takes args individually, apply takes array', isCorrect: true }, { text: 'apply faster', isCorrect: false }, { text: 'None', isCorrect: false }], explanation: 'Argument passing difference.', points: 20 },

  // --- TYPESCRIPT (20) ---
  { technology: 'TypeScript', category: 'Language', difficulty: 'medium', question: 'How does TypeScript improve maintainability and scalability in large JavaScript applications?', options: [{ text: 'By improving runtime performance', isCorrect: false }, { text: 'By adding static typing and early error detection during development', isCorrect: true }, { text: 'By reducing file size', isCorrect: false }, { text: 'By removing JavaScript', isCorrect: false }], explanation: 'Static typing and error detection.', points: 15 },
  { technology: 'TypeScript', category: 'Language', difficulty: 'medium', question: 'What is the difference between interface and type in TypeScript?', options: [{ text: 'No difference', isCorrect: false }, { text: 'Interface is extendable, type is more flexible for unions/intersections', isCorrect: true }, { text: 'Type is faster', isCorrect: false }, { text: 'Interface cannot be reused', isCorrect: false }], explanation: 'Interfaces are more object-oriented extendable.', points: 15 },
  { technology: 'TypeScript', category: 'Language', difficulty: 'medium', question: 'How does TypeScript handle type inference when explicit types are not provided?', options: [{ text: 'Throws error', isCorrect: false }, { text: 'Automatically infers types based on assigned values', isCorrect: true }, { text: 'Assigns any', isCorrect: false }, { text: 'Ignores variables', isCorrect: false }], explanation: 'Automatic inference.', points: 15 },
  { technology: 'TypeScript', category: 'Language', difficulty: 'hard', question: 'What is the purpose of generics in TypeScript?', options: [{ text: 'Improve UI', isCorrect: false }, { text: 'Create reusable components with flexible types', isCorrect: true }, { text: 'Avoid functions', isCorrect: false }, { text: 'Handle APIs', isCorrect: false }], explanation: 'Flexible types.', points: 20 },
  { technology: 'TypeScript', category: 'Language', difficulty: 'medium', question: 'What problem does the any type introduce in TypeScript applications?', options: [{ text: 'Performance issues', isCorrect: false }, { text: 'Loss of type safety', isCorrect: true }, { text: 'Syntax error', isCorrect: false }, { text: 'Memory leak', isCorrect: false }], explanation: 'Bypasses type safety.', points: 15 },
  { technology: 'TypeScript', category: 'Language', difficulty: 'hard', question: 'What is the role of unknown type compared to any?', options: [{ text: 'Same behavior', isCorrect: false }, { text: 'unknown is safer because it requires type checking before usage', isCorrect: true }, { text: 'unknown is faster', isCorrect: false }, { text: 'unknown is deprecated', isCorrect: false }], explanation: 'Safer than any.', points: 20 },
  { technology: 'TypeScript', category: 'Language', difficulty: 'medium', question: 'What is a union type in TypeScript?', options: [{ text: 'Multiple functions', isCorrect: false }, { text: 'Variable that can hold multiple types', isCorrect: true }, { text: 'Single type', isCorrect: false }, { text: 'API', isCorrect: false }], explanation: 'Holds multiple types.', points: 15 },
  { technology: 'TypeScript', category: 'Language', difficulty: 'hard', question: 'What is an intersection type?', options: [{ text: 'Combine multiple types into one', isCorrect: true }, { text: 'Split types', isCorrect: false }, { text: 'Remove types', isCorrect: false }, { text: 'API', isCorrect: false }], explanation: 'Combines types.', points: 20 },
  { technology: 'TypeScript', category: 'Language', difficulty: 'medium', question: 'What is the purpose of readonly in TypeScript?', options: [{ text: 'Improves speed', isCorrect: false }, { text: 'Prevents reassignment of properties', isCorrect: true }, { text: 'Removes variables', isCorrect: false }, { text: 'API', isCorrect: false }], explanation: 'Prevents reassignment.', points: 15 },
  { technology: 'TypeScript', category: 'Language', difficulty: 'medium', question: 'What is the benefit of using enums in TypeScript?', options: [{ text: 'UI improvement', isCorrect: false }, { text: 'Define a set of named constants for better readability', isCorrect: true }, { text: 'Reduce memory', isCorrect: false }, { text: 'API', isCorrect: false }], explanation: 'Named constants.', points: 15 },
  { technology: 'TypeScript', category: 'Language', difficulty: 'hard', question: 'What is type narrowing in TypeScript?', options: [{ text: 'Expanding types', isCorrect: false }, { text: 'Refining a type based on conditions', isCorrect: true }, { text: 'Removing types', isCorrect: false }, { text: 'API', isCorrect: false }], explanation: 'Refining types.', points: 20 },
  { technology: 'TypeScript', category: 'Language', difficulty: 'hard', question: 'What is the purpose of as keyword in TypeScript?', options: [{ text: 'Loop', isCorrect: false }, { text: 'Type assertion to override inferred type', isCorrect: true }, { text: 'API', isCorrect: false }, { text: 'Routing', isCorrect: false }], explanation: 'Type assertion.', points: 20 },
  { technology: 'TypeScript', category: 'Language', difficulty: 'medium', question: 'What is the difference between null and undefined in TypeScript strict mode?', options: [{ text: 'Same', isCorrect: false }, { text: 'Treated as distinct types', isCorrect: true }, { text: 'Both ignored', isCorrect: false }, { text: 'Both strings', isCorrect: false }], explanation: 'Distinct types.', points: 15 },
  { technology: 'TypeScript', category: 'Language', difficulty: 'medium', question: 'What is optional chaining (?.) used for?', options: [{ text: 'Loop', isCorrect: false }, { text: 'Safely accessing nested properties without errors', isCorrect: true }, { text: 'API', isCorrect: false }, { text: 'Routing', isCorrect: false }], explanation: 'Safe property access.', points: 15 },
  { technology: 'TypeScript', category: 'Language', difficulty: 'medium', question: 'What is the role of tsconfig.json in a TypeScript project?', options: [{ text: 'Styling', isCorrect: false }, { text: 'Configure compiler options and project settings', isCorrect: true }, { text: 'Routing', isCorrect: false }, { text: 'API', isCorrect: false }], explanation: 'Compiler configuration.', points: 15 },
  { technology: 'TypeScript', category: 'Language', difficulty: 'hard', question: 'What is a mapped type in TypeScript?', options: [{ text: 'Loop', isCorrect: false }, { text: 'Create new types by transforming existing ones', isCorrect: true }, { text: 'API', isCorrect: false }, { text: 'Routing', isCorrect: false }], explanation: 'Transforms types.', points: 20 },
  { technology: 'TypeScript', category: 'Language', difficulty: 'hard', question: 'What is the purpose of decorators in TypeScript?', options: [{ text: 'Styling', isCorrect: false }, { text: 'Add metadata and modify class behavior (experimental feature)', isCorrect: true }, { text: 'API', isCorrect: false }, { text: 'DB', isCorrect: false }], explanation: 'Metadata and class modification.', points: 20 },
  { technology: 'TypeScript', category: 'Language', difficulty: 'medium', question: 'What is strict mode in TypeScript?', options: [{ text: 'Ignore errors', isCorrect: false }, { text: 'Enable strict type checking options', isCorrect: true }, { text: 'Disable checks', isCorrect: false }, { text: 'API', isCorrect: false }], explanation: 'Strict type checking.', points: 15 },
  { technology: 'TypeScript', category: 'Language', difficulty: 'hard', question: 'What is the difference between compile-time and runtime errors in TypeScript?', options: [{ text: 'Same', isCorrect: false }, { text: 'Compile-time detected by TS, runtime occurs in JS execution', isCorrect: true }, { text: 'Runtime faster', isCorrect: false }, { text: 'None', isCorrect: false }], explanation: 'TS detects errors vs execution errors.', points: 20 },
  { technology: 'TypeScript', category: 'Language', difficulty: 'medium', question: 'How does TypeScript integrate with existing JavaScript projects?', options: [{ text: 'Cannot integrate', isCorrect: false }, { text: 'Gradual adoption by renaming files and adding types', isCorrect: true }, { text: 'Replace JS', isCorrect: false }, { text: 'API', isCorrect: false }], explanation: 'Gradual adoption.', points: 15 }
];

async function seed() {
  await connectDB();
  await Question.insertMany(techData);
  console.log(`Seed successful! Inserted ${techData.length} questions total.`);
  process.exit();
}
seed();
