const mongoose = require('mongoose');
const Question = require('../models/Question');
const connectDB = require('../config/database');

const k8sAndGraphQLQuestions = [
  // --- KUBERNETES (20) ---
  { technology: 'Kubernetes', category: 'DevOps', difficulty: 'medium', question: 'What problem does Kubernetes solve in containerized applications?', options: [{ text: 'UI', isCorrect: false }, { text: 'Container orchestration and scaling', isCorrect: true }, { text: 'API', isCorrect: false }, { text: 'DB', isCorrect: false }], explanation: 'Orchestration and scaling.', points: 15 },
  { technology: 'Kubernetes', category: 'DevOps', difficulty: 'medium', question: 'What is a Pod in Kubernetes architecture?', options: [{ text: 'VM', isCorrect: false }, { text: 'Smallest deployable unit containing one or more containers', isCorrect: true }, { text: 'API', isCorrect: false }, { text: 'DB', isCorrect: false }], explanation: 'Smallest deployable unit.', points: 15 },
  { technology: 'Kubernetes', category: 'DevOps', difficulty: 'medium', question: 'What is the role of a Deployment in Kubernetes?', options: [{ text: 'UI', isCorrect: false }, { text: 'Manage replica sets and ensure desired state of pods', isCorrect: true }, { text: 'API', isCorrect: false }, { text: 'DB', isCorrect: false }], explanation: 'Ensures desired state of pods.', points: 15 },
  { technology: 'Kubernetes', category: 'DevOps', difficulty: 'medium', question: 'What is the purpose of a Service in Kubernetes?', options: [{ text: 'UI', isCorrect: false }, { text: 'Expose pods and enable communication', isCorrect: true }, { text: 'DB', isCorrect: false }, { text: 'API', isCorrect: false }], explanation: 'Networking and service discovery.', points: 15 },
  { technology: 'Kubernetes', category: 'DevOps', difficulty: 'medium', question: 'What is horizontal scaling in Kubernetes?', options: [{ text: 'Increase CPU', isCorrect: false }, { text: 'Increase number of pods', isCorrect: true }, { text: 'Increase memory', isCorrect: false }, { text: 'Reduce pods', isCorrect: false }], explanation: 'Scale pod count.', points: 15 },
  { technology: 'Kubernetes', category: 'DevOps', difficulty: 'medium', question: 'What is the role of kube-scheduler?', options: [{ text: 'API', isCorrect: false }, { text: 'Assign pods to nodes based on resources', isCorrect: true }, { text: 'DB', isCorrect: false }, { text: 'UI', isCorrect: false }], explanation: 'Schedules pods onto nodes.', points: 15 },
  { technology: 'Kubernetes', category: 'DevOps', difficulty: 'medium', question: 'What is a ConfigMap used for?', options: [{ text: 'DB', isCorrect: false }, { text: 'Store configuration data separate from code', isCorrect: true }, { text: 'UI', isCorrect: false }, { text: 'API', isCorrect: false }], explanation: 'Configuration storage.', points: 15 },
  { technology: 'Kubernetes', category: 'DevOps', difficulty: 'medium', question: 'What is a Secret in Kubernetes?', options: [{ text: 'UI', isCorrect: false }, { text: 'Store sensitive data like passwords securely', isCorrect: true }, { text: 'API', isCorrect: false }, { text: 'DB', isCorrect: false }], explanation: 'Sensitive data management.', points: 15 },
  { technology: 'Kubernetes', category: 'DevOps', difficulty: 'hard', question: 'What is rolling deployment?', options: [{ text: 'Stop all pods', isCorrect: false }, { text: 'Gradually update pods without downtime', isCorrect: true }, { text: 'Delete pods', isCorrect: false }, { text: 'Restart cluster', isCorrect: false }], explanation: 'Zero-downtime updates.', points: 20 },
  { technology: 'Kubernetes', category: 'DevOps', difficulty: 'hard', question: 'What is the role of Ingress?', options: [{ text: 'DB', isCorrect: false }, { text: 'Manage external access to services (HTTP/HTTPS routing)', isCorrect: true }, { text: 'UI', isCorrect: false }, { text: 'API', isCorrect: false }], explanation: 'External traffic routing.', points: 20 },
  { technology: 'Kubernetes', category: 'DevOps', difficulty: 'medium', question: 'What is auto-scaling in Kubernetes?', options: [{ text: 'Manual scaling', isCorrect: false }, { text: 'Automatically adjust pods based on load', isCorrect: true }, { text: 'API', isCorrect: false }, { text: 'DB', isCorrect: false }], explanation: 'Automated pod adjustment.', points: 15 },
  { technology: 'Kubernetes', category: 'DevOps', difficulty: 'medium', question: 'What is node in Kubernetes?', options: [{ text: 'Worker machine running containers', isCorrect: true }, { text: 'Pod', isCorrect: false }, { text: 'Cluster', isCorrect: false }, { text: 'App', isCorrect: false }], explanation: 'Physical or virtual worker node.', points: 15 },
  { technology: 'Kubernetes', category: 'DevOps', difficulty: 'medium', question: 'What is cluster in Kubernetes?', options: [{ text: 'Single pod', isCorrect: false }, { text: 'Group of nodes managed together', isCorrect: true }, { text: 'Container', isCorrect: false }, { text: 'API', isCorrect: false }], explanation: 'Coordinated set of nodes.', points: 15 },
  { technology: 'Kubernetes', category: 'DevOps', difficulty: 'hard', question: 'What is etcd in Kubernetes?', options: [{ text: 'UI', isCorrect: false }, { text: 'Distributed key-value store for cluster data', isCorrect: true }, { text: 'API', isCorrect: false }, { text: 'DB', isCorrect: false }], explanation: 'Cluster source of truth.', points: 20 },
  { technology: 'Kubernetes', category: 'DevOps', difficulty: 'medium', question: 'What is the purpose of labels in Kubernetes?', options: [{ text: 'UI', isCorrect: false }, { text: 'Identify and organize resources', isCorrect: true }, { text: 'API', isCorrect: false }, { text: 'DB', isCorrect: false }], explanation: 'Organizing resources.', points: 15 },
  { technology: 'Kubernetes', category: 'DevOps', difficulty: 'medium', question: 'What is namespace in Kubernetes?', options: [{ text: 'API', isCorrect: false }, { text: 'Logical separation of resources within cluster', isCorrect: true }, { text: 'DB', isCorrect: false }, { text: 'UI', isCorrect: false }], explanation: 'Logical multi-tenancy.', points: 15 },
  { technology: 'Kubernetes', category: 'DevOps', difficulty: 'medium', question: 'What is the role of kubelet?', options: [{ text: 'API', isCorrect: false }, { text: 'Ensures containers are running in pods on node', isCorrect: true }, { text: 'DB', isCorrect: false }, { text: 'UI', isCorrect: false }], explanation: 'Node-level agent.', points: 15 },
  { technology: 'Kubernetes', category: 'DevOps', difficulty: 'hard', question: 'What is persistent volume?', options: [{ text: 'UI', isCorrect: false }, { text: 'Storage resource independent of pod lifecycle', isCorrect: true }, { text: 'API', isCorrect: false }, { text: 'DB', isCorrect: false }], explanation: 'Decoupled persistent storage.', points: 20 },
  { technology: 'Kubernetes', category: 'DevOps', difficulty: 'medium', question: 'What is Helm in Kubernetes?', options: [{ text: 'UI', isCorrect: false }, { text: 'Package manager for Kubernetes applications', isCorrect: true }, { text: 'API', isCorrect: false }, { text: 'DB', isCorrect: false }], explanation: 'Kubernetes package manager.', points: 15 },
  { technology: 'Kubernetes', category: 'DevOps', difficulty: 'hard', question: 'What is the main advantage of Kubernetes over Docker alone?', options: [{ text: 'UI', isCorrect: false }, { text: 'Advanced orchestration, scaling, and management of containers', isCorrect: true }, { text: 'DB', isCorrect: false }, { text: 'API', isCorrect: false }], explanation: 'Orchestration and cluster management.', points: 20 },

  // --- GRAPHQL (20) ---
  { technology: 'GraphQL', category: 'API', difficulty: 'medium', question: 'What problem does GraphQL solve compared to REST APIs?', options: [{ text: 'UI', isCorrect: false }, { text: 'Over-fetching and under-fetching of data', isCorrect: true }, { text: 'DB', isCorrect: false }, { text: 'CSS', isCorrect: false }], explanation: 'Precise data fetching.', points: 15 },
  { technology: 'GraphQL', category: 'API', difficulty: 'medium', question: 'What is a resolver in GraphQL?', options: [{ text: 'UI', isCorrect: false }, { text: 'Function that resolves a query field to data', isCorrect: true }, { text: 'DB', isCorrect: false }, { text: 'API', isCorrect: false }], explanation: 'Data fetching function.', points: 15 },
  { technology: 'GraphQL', category: 'API', difficulty: 'medium', question: 'What is schema in GraphQL?', options: [{ text: 'UI', isCorrect: false }, { text: 'Defines structure of API including types and queries', isCorrect: true }, { text: 'DB', isCorrect: false }, { text: 'CSS', isCorrect: false }], explanation: 'Contract for data.', points: 15 },
  { technology: 'GraphQL', category: 'API', difficulty: 'medium', question: 'What is the difference between query and mutation?', options: [{ text: 'Same', isCorrect: false }, { text: 'Query = read, Mutation = write/update data', isCorrect: true }, { text: 'Mutation faster', isCorrect: false }, { text: 'Query updates', isCorrect: false }], explanation: 'Read vs Write operation.', points: 15 },
  { technology: 'GraphQL', category: 'API', difficulty: 'medium', question: 'What is the role of type system in GraphQL?', options: [{ text: 'UI', isCorrect: false }, { text: 'Strongly typed schema for validation and structure', isCorrect: true }, { text: 'DB', isCorrect: false }, { text: 'CSS', isCorrect: false }], explanation: 'Strong typing benefits.', points: 15 },
  { technology: 'GraphQL', category: 'API', difficulty: 'medium', question: 'What is over-fetching in REST APIs?', options: [{ text: 'Less data', isCorrect: false }, { text: 'Fetching unnecessary data', isCorrect: true }, { text: 'API error', isCorrect: false }, { text: 'DB', isCorrect: false }], explanation: 'Too much unwanted data.', points: 15 },
  { technology: 'GraphQL', category: 'API', difficulty: 'medium', question: 'What is under-fetching?', options: [{ text: 'Too much data', isCorrect: false }, { text: 'Multiple requests needed to get required data', isCorrect: true }, { text: 'API error', isCorrect: false }, { text: 'DB', isCorrect: false }], explanation: 'Missing related data.', points: 15 },
  { technology: 'GraphQL', category: 'API', difficulty: 'hard', question: 'What is introspection in GraphQL?', options: [{ text: 'UI', isCorrect: false }, { text: 'Ability to query schema for its structure', isCorrect: true }, { text: 'DB', isCorrect: false }, { text: 'CSS', isCorrect: false }], explanation: 'Schema self-discovery.', points: 20 },
  { technology: 'GraphQL', category: 'API', difficulty: 'medium', question: 'What is a fragment in GraphQL?', options: [{ text: 'UI', isCorrect: false }, { text: 'Reusable query parts', isCorrect: true }, { text: 'DB', isCorrect: false }, { text: 'API', isCorrect: false }], explanation: 'Reusable selection set.', points: 15 },
  { technology: 'GraphQL', category: 'API', difficulty: 'hard', question: 'What is batching in GraphQL?', options: [{ text: 'UI', isCorrect: false }, { text: 'Combine multiple requests into one', isCorrect: true }, { text: 'DB', isCorrect: false }, { text: 'CSS', isCorrect: false }], explanation: 'Network request optimization.', points: 20 },
  { technology: 'GraphQL', category: 'API', difficulty: 'hard', question: 'What is N+1 problem in GraphQL?', options: [{ text: 'UI', isCorrect: false }, { text: 'Multiple DB queries per request leading to inefficiency', isCorrect: true }, { text: 'API', isCorrect: false }, { text: 'CSS', isCorrect: false }], explanation: 'Repeated query inefficiency.', points: 20 },
  { technology: 'GraphQL', category: 'API', difficulty: 'hard', question: 'How can N+1 problem be solved?', options: [{ text: 'API', isCorrect: false }, { text: 'Using DataLoader or batching techniques', isCorrect: true }, { text: 'DB', isCorrect: false }, { text: 'CSS', isCorrect: false }], explanation: 'DataLoader technique.', points: 20 },
  { technology: 'GraphQL', category: 'API', difficulty: 'hard', question: 'What is subscription in GraphQL?', options: [{ text: 'UI', isCorrect: false }, { text: 'Real-time updates using WebSockets', isCorrect: true }, { text: 'DB', isCorrect: false }, { text: 'CSS', isCorrect: false }], explanation: 'Real-time data streaming.', points: 20 },
  { technology: 'GraphQL', category: 'API', difficulty: 'medium', question: 'What is the role of variables in GraphQL queries?', options: [{ text: 'UI', isCorrect: false }, { text: 'Pass dynamic values into queries', isCorrect: true }, { text: 'DB', isCorrect: false }, { text: 'CSS', isCorrect: false }], explanation: 'Dynamic data injection.', points: 15 },
  { technology: 'GraphQL', category: 'API', difficulty: 'medium', question: 'What is the benefit of a single endpoint in GraphQL?', options: [{ text: 'UI', isCorrect: false }, { text: 'Simplifies API management and querying', isCorrect: true }, { text: 'DB', isCorrect: false }, { text: 'CSS', isCorrect: false }], explanation: 'Centralized access point.', points: 15 },
  { technology: 'GraphQL', category: 'API', difficulty: 'hard', question: 'What is schema stitching/federation?', options: [{ text: 'UI', isCorrect: false }, { text: 'Combine multiple GraphQL services into one API', isCorrect: true }, { text: 'DB', isCorrect: false }, { text: 'CSS', isCorrect: false }], explanation: 'Microservice API aggregation.', points: 20 },
  { technology: 'GraphQL', category: 'API', difficulty: 'medium', question: 'What is strongly typed nature advantage in GraphQL?', options: [{ text: 'UI', isCorrect: false }, { text: 'Better validation and developer experience', isCorrect: true }, { text: 'DB', isCorrect: false }, { text: 'CSS', isCorrect: false }], explanation: 'Enhanced dev experience.', points: 15 },
  { technology: 'GraphQL', category: 'API', difficulty: 'medium', question: 'What is directive in GraphQL?', options: [{ text: 'UI', isCorrect: false }, { text: 'Add conditional logic to queries (e.g., @include)', isCorrect: true }, { text: 'DB', isCorrect: false }, { text: 'CSS', isCorrect: false }], explanation: 'Conditional query logic.', points: 15 },
  { technology: 'GraphQL', category: 'API', difficulty: 'hard', question: 'What is caching challenge in GraphQL compared to REST?', options: [{ text: 'No challenge', isCorrect: false }, { text: 'Difficult due to flexible queries', isCorrect: true }, { text: 'Easy', isCorrect: false }, { text: 'DB', isCorrect: false }], explanation: 'Caching complexity.', points: 20 },
  { technology: 'GraphQL', category: 'API', difficulty: 'medium', question: 'What is the main drawback of GraphQL?', options: [{ text: 'UI', isCorrect: false }, { text: 'Complexity in implementation and caching', isCorrect: true }, { text: 'DB', isCorrect: false }, { text: 'CSS', isCorrect: false }], explanation: 'Overhead in implementation.', points: 15 }
];

async function seed() {
  await connectDB();
  await Question.insertMany(k8sAndGraphQLQuestions);
  console.log(`Seed successful! Inserted ${k8sAndGraphQLQuestions.length} K8s/GraphQL questions.`);
  process.exit();
}
seed();
