const mongoose = require('mongoose');
const Question = require('../models/Question');
const connectDB = require('../config/database');

const allRemainingQuestions = [
  // --- CSS3 (20) ---
  { technology: 'CSS3', category: 'Frontend', difficulty: 'easy', question: 'Which CSS property is used to change the text color of an element?', options: [{ text: 'font-style', isCorrect: false }, { text: 'text-align', isCorrect: false }, { text: 'color', isCorrect: true }, { text: 'background-color', isCorrect: false }], explanation: 'Color property changes text color.', points: 10 },
  { technology: 'CSS3', category: 'Frontend', difficulty: 'easy', question: 'What does display: flex do in CSS?', options: [{ text: 'Makes elements invisible', isCorrect: false }, { text: 'Enables flexbox layout for flexible positioning', isCorrect: true }, { text: 'Converts block to inline', isCorrect: false }, { text: 'Adds animation', isCorrect: false }], explanation: 'Enables flexbox layout.', points: 10 },
  { technology: 'CSS3', category: 'Frontend', difficulty: 'easy', question: 'Which unit is relative to the font size of the parent element?', options: [{ text: 'px', isCorrect: false }, { text: 'em', isCorrect: true }, { text: 'cm', isCorrect: false }, { text: 'pt', isCorrect: false }], explanation: 'em is relative to parent font size.', points: 10 },
  { technology: 'CSS3', category: 'Frontend', difficulty: 'medium', question: 'What is the purpose of the z-index property?', options: [{ text: 'Controls font size', isCorrect: false }, { text: 'Specifies stacking order of elements', isCorrect: true }, { text: 'Adds shadow', isCorrect: false }, { text: 'Aligns text', isCorrect: false }], explanation: 'Specifies stacking order.', points: 15 },
  { technology: 'CSS3', category: 'Frontend', difficulty: 'easy', question: 'Which property is used to create rounded corners?', options: [{ text: 'border-style', isCorrect: false }, { text: 'border-radius', isCorrect: true }, { text: 'padding', isCorrect: false }, { text: 'margin', isCorrect: false }], explanation: 'Border-radius creates rounded corners.', points: 10 },
  { technology: 'CSS3', category: 'Frontend', difficulty: 'medium', question: 'What does position: absolute mean?', options: [{ text: 'Positioned relative to nearest positioned ancestor', isCorrect: true }, { text: 'Fixed to viewport', isCorrect: false }, { text: 'Inline positioning', isCorrect: false }, { text: 'Default positioning', isCorrect: false }], explanation: 'Positioned relative to ancestor.', points: 15 },
  { technology: 'CSS3', category: 'Frontend', difficulty: 'easy', question: 'Which property controls content overflow?', options: [{ text: 'flow', isCorrect: false }, { text: 'overflow', isCorrect: true }, { text: 'clip', isCorrect: false }, { text: 'display', isCorrect: false }], explanation: 'Overflow property.', points: 10 },
  { technology: 'CSS3', category: 'Frontend', difficulty: 'medium', question: 'What is the use of @media rule?', options: [{ text: 'Font styling', isCorrect: false }, { text: 'Responsive design based on screen size', isCorrect: true }, { text: 'Animation control', isCorrect: false }, { text: 'Grid layout', isCorrect: false }], explanation: 'Used for media queries.', points: 15 },
  { technology: 'CSS3', category: 'Frontend', difficulty: 'easy', question: 'Which property is used to add shadow to elements?', options: [{ text: 'shadow', isCorrect: false }, { text: 'box-shadow', isCorrect: true }, { text: 'text-glow', isCorrect: false }, { text: 'filter-shadow', isCorrect: false }], explanation: 'box-shadow adds shadow.', points: 10 },
  { technology: 'CSS3', category: 'Frontend', difficulty: 'easy', question: 'What is the default display value of a <div> element?', options: [{ text: 'inline', isCorrect: false }, { text: 'block', isCorrect: true }, { text: 'flex', isCorrect: false }, { text: 'grid', isCorrect: false }], explanation: 'Div defaults to block.', points: 10 },
  { technology: 'CSS3', category: 'Frontend', difficulty: 'medium', question: 'Which property defines the main axis in flexbox?', options: [{ text: 'align-items', isCorrect: false }, { text: 'justify-content', isCorrect: false }, { text: 'flex-direction', isCorrect: true }, { text: 'flex-wrap', isCorrect: false }], explanation: 'flex-direction sets axis.', points: 15 },
  { technology: 'CSS3', category: 'Frontend', difficulty: 'medium', question: 'What does display: grid enable?', options: [{ text: 'Inline layout', isCorrect: false }, { text: '2D grid-based layout system', isCorrect: true }, { text: 'Animation', isCorrect: false }, { text: 'Positioning', isCorrect: false }], explanation: '2D layout system.', points: 15 },
  { technology: 'CSS3', category: 'Frontend', difficulty: 'easy', question: 'Which pseudo-class applies styles when a user hovers over an element?', options: [{ text: ':active', isCorrect: false }, { text: ':hover', isCorrect: true }, { text: ':focus', isCorrect: false }, { text: ':visited', isCorrect: false }], explanation: 'Hover pseudo-class.', points: 10 },
  { technology: 'CSS3', category: 'Frontend', difficulty: 'medium', question: 'Which property is used for smooth transitions?', options: [{ text: 'animation', isCorrect: false }, { text: 'transition', isCorrect: true }, { text: 'transform', isCorrect: false }, { text: 'timing', isCorrect: false }], explanation: 'Transition handles smoothness.', points: 15 },
  { technology: 'CSS3', category: 'Frontend', difficulty: 'medium', question: 'What does vh unit represent?', options: [{ text: 'View height (percentage of viewport height)', isCorrect: true }, { text: 'Variable height', isCorrect: false }, { text: 'Vertical margin', isCorrect: false }, { text: 'Visible height', isCorrect: false }], explanation: 'Viewport height percentage.', points: 15 },
  { technology: 'CSS3', category: 'Frontend', difficulty: 'medium', question: 'Which property aligns items vertically in flexbox?', options: [{ text: 'justify-content', isCorrect: false }, { text: 'align-items', isCorrect: true }, { text: 'flex-direction', isCorrect: false }, { text: 'order', isCorrect: false }], explanation: 'Align-items handles vertical.', points: 15 },
  { technology: 'CSS3', category: 'Frontend', difficulty: 'hard', question: 'Which has highest specificity in CSS?', options: [{ text: 'Class', isCorrect: false }, { text: 'ID', isCorrect: false }, { text: 'Inline styles', isCorrect: true }, { text: 'Element', isCorrect: false }], explanation: 'Inline styles have highest specificity.', points: 20 },
  { technology: 'CSS3', category: 'Frontend', difficulty: 'medium', question: 'Which function is used to access CSS variables?', options: [{ text: 'get()', isCorrect: false }, { text: 'var()', isCorrect: true }, { text: 'value()', isCorrect: false }, { text: 'css()', isCorrect: false }], explanation: 'var() function access.', points: 15 },
  { technology: 'CSS3', category: 'Frontend', difficulty: 'medium', question: 'Which property prevents text from wrapping?', options: [{ text: 'text-wrap', isCorrect: false }, { text: 'white-space', isCorrect: true }, { text: 'overflow', isCorrect: false }, { text: 'word-break', isCorrect: false }], explanation: 'White-space prevents wrap.', points: 15 },
  { technology: 'CSS3', category: 'Frontend', difficulty: 'medium', question: 'Which layout system is primarily two-dimensional?', options: [{ text: 'Flexbox', isCorrect: false }, { text: 'CSS Grid', isCorrect: true }, { text: 'Inline', isCorrect: false }, { text: 'Block', isCorrect: false }], explanation: 'CSS Grid is 2D.', points: 15 },

  // --- NEXT.JS (20) ---
  { technology: 'Next.js', category: 'Frontend', difficulty: 'easy', question: 'Next.js is primarily built on which library?', options: [{ text: 'Angular', isCorrect: false }, { text: 'Vue', isCorrect: false }, { text: 'React', isCorrect: true }, { text: 'jQuery', isCorrect: false }], explanation: 'Based on React.', points: 10 },
  { technology: 'Next.js', category: 'Frontend', difficulty: 'medium', question: 'What does SSR stand for in Next.js?', options: [{ text: 'Static Server Rendering', isCorrect: false }, { text: 'Server-Side Rendering', isCorrect: true }, { text: 'Secure State Rendering', isCorrect: false }, { text: 'System Service Rendering', isCorrect: false }], explanation: 'Server-Side Rendering.', points: 15 },
  { technology: 'Next.js', category: 'Frontend', difficulty: 'easy', question: 'How does Next.js handle routing?', options: [{ text: 'Manual routing', isCorrect: false }, { text: 'File-based routing', isCorrect: true }, { text: 'API-based routing', isCorrect: false }, { text: 'URL mapping', isCorrect: false }], explanation: 'File-based routing.', points: 10 },
  { technology: 'Next.js', category: 'Frontend', difficulty: 'medium', question: 'Where are API routes typically created?', options: [{ text: '/components', isCorrect: false }, { text: '/pages/api', isCorrect: true }, { text: '/public', isCorrect: false }, { text: '/utils', isCorrect: false }], explanation: 'Pages/api directory.', points: 15 },
  { technology: 'Next.js', category: 'Frontend', difficulty: 'medium', question: 'Which function is used for static site generation?', options: [{ text: 'getServerSideProps', isCorrect: false }, { text: 'getStaticProps', isCorrect: true }, { text: 'useEffect', isCorrect: false }, { text: 'fetchData', isCorrect: false }], explanation: 'getStaticProps.', points: 15 },
  { technology: 'Next.js', category: 'Frontend', difficulty: 'medium', question: 'How do you define dynamic routes in Next.js?', options: [{ text: '(id).js', isCorrect: false }, { text: '{id}.js', isCorrect: false }, { text: '[id].js', isCorrect: true }, { text: '<id>.js', isCorrect: false }], explanation: 'Bracket notation [id].js.', points: 15 },
  { technology: 'Next.js', category: 'Frontend', difficulty: 'medium', question: 'Which component is used for optimized images?', options: [{ text: '<img>', isCorrect: false }, { text: '<Image />', isCorrect: true }, { text: '<Pic />', isCorrect: false }, { text: '<Media />', isCorrect: false }], explanation: 'Image component.', points: 15 },
  { technology: 'Next.js', category: 'Frontend', difficulty: 'easy', question: 'Which component is used for navigation?', options: [{ text: '<Router>', isCorrect: false }, { text: '<Navigate>', isCorrect: false }, { text: '<Link />', isCorrect: true }, { text: '<Route />', isCorrect: false }], explanation: 'Link component.', points: 10 },
  { technology: 'Next.js', category: 'Frontend', difficulty: 'medium', question: 'What is Incremental Static Regeneration (ISR)?', options: [{ text: 'Dynamic rendering', isCorrect: false }, { text: 'Updating static pages after build', isCorrect: true }, { text: 'Server restart', isCorrect: false }, { text: 'Cache clearing', isCorrect: false }], explanation: 'Updates static pages post-build.', points: 15 },
  { technology: 'Next.js', category: 'Frontend', difficulty: 'easy', question: 'Which company maintains Next.js?', options: [{ text: 'Google', isCorrect: false }, { text: 'Meta', isCorrect: false }, { text: 'Vercel', isCorrect: true }, { text: 'Microsoft', isCorrect: false }], explanation: 'Maintained by Vercel.', points: 10 },
  { technology: 'Next.js', category: 'Frontend', difficulty: 'medium', question: 'When does getServerSideProps run?', options: [{ text: 'Build time', isCorrect: false }, { text: 'Runtime on server', isCorrect: true }, { text: 'Client side', isCorrect: false }, { text: 'Only once', isCorrect: false }], explanation: 'Runtime server-side.', points: 15 },
  { technology: 'Next.js', category: 'Frontend', difficulty: 'easy', question: 'What prefix is used for public environment variables?', options: [{ text: 'APP_', isCorrect: false }, { text: 'NEXT_PUBLIC_', isCorrect: true }, { text: 'ENV_', isCorrect: false }, { text: 'PUBLIC_', isCorrect: false }], explanation: 'NEXT_PUBLIC_ prefix.', points: 10 },
  { technology: 'Next.js', category: 'Frontend', difficulty: 'medium', question: 'Which directory was introduced in Next.js 13?', options: [{ text: 'src', isCorrect: false }, { text: 'app', isCorrect: true }, { text: 'build', isCorrect: false }, { text: 'pages2', isCorrect: false }], explanation: 'App router.', points: 15 },
  { technology: 'Next.js', category: 'Frontend', difficulty: 'medium', question: 'What does next export do?', options: [{ text: 'Deploy app', isCorrect: false }, { text: 'Creates static site', isCorrect: true }, { text: 'Starts server', isCorrect: false }, { text: 'Compiles code', isCorrect: false }], explanation: 'Creates static build.', points: 15 },
  { technology: 'Next.js', category: 'Frontend', difficulty: 'medium', question: 'Which hook is used for routing?', options: [{ text: 'useState', isCorrect: false }, { text: 'useRouter', isCorrect: true }, { text: 'useEffect', isCorrect: false }, { text: 'useNavigate', isCorrect: false }], explanation: 'useRouter hook.', points: 15 },
  { technology: 'Next.js', category: 'Frontend', difficulty: 'medium', question: 'What is middleware used for?', options: [{ text: 'UI design', isCorrect: false }, { text: 'Request interception', isCorrect: true }, { text: 'Data storage', isCorrect: false }, { text: 'Styling', isCorrect: false }], explanation: 'Request interception.', points: 15 },
  { technology: 'Next.js', category: 'Frontend', difficulty: 'medium', question: 'Which rendering method fetches data at request time?', options: [{ text: 'SSG', isCorrect: false }, { text: 'CSR', isCorrect: false }, { text: 'SSR', isCorrect: true }, { text: 'ISR', isCorrect: false }], explanation: 'SSR fetches at request.', points: 15 },
  { technology: 'Next.js', category: 'Frontend', difficulty: 'medium', question: 'What is <Head> component used for?', options: [{ text: 'Layout', isCorrect: false }, { text: 'Metadata and SEO', isCorrect: true }, { text: 'Navigation', isCorrect: false }, { text: 'Styling', isCorrect: false }], explanation: 'Metadata/SEO control.', points: 15 },
  { technology: 'Next.js', category: 'Frontend', difficulty: 'medium', question: 'Next.js API routes run on?', options: [{ text: 'Browser', isCorrect: false }, { text: 'Node.js server', isCorrect: true }, { text: 'Database', isCorrect: false }, { text: 'CDN', isCorrect: false }], explanation: 'Node.js runtime.', points: 15 },
  { technology: 'Next.js', category: 'Frontend', difficulty: 'medium', question: 'Default bundler used by Next.js?', options: [{ text: 'Rollup', isCorrect: false }, { text: 'Parcel', isCorrect: false }, { text: 'Webpack', isCorrect: true }, { text: 'Vite', isCorrect: false }], explanation: 'Webpack default.', points: 15 },

  // --- PYTHON (20) ---
  { technology: 'Python', category: 'Language', difficulty: 'easy', question: 'What type of language is Python?', options: [{ text: 'Compiled', isCorrect: false }, { text: 'Interpreted', isCorrect: true }, { text: 'Assembly', isCorrect: false }, { text: 'Binary', isCorrect: false }], explanation: 'Interpreted language.', points: 10 },
  { technology: 'Python', category: 'Language', difficulty: 'easy', question: 'Which keyword defines a function?', options: [{ text: 'func', isCorrect: false }, { text: 'def', isCorrect: true }, { text: 'function', isCorrect: false }, { text: 'define', isCorrect: false }], explanation: 'def keyword.', points: 10 },
  { technology: 'Python', category: 'Language', difficulty: 'easy', question: 'Which data type is mutable?', options: [{ text: 'Tuple', isCorrect: false }, { text: 'String', isCorrect: false }, { text: 'List', isCorrect: true }, { text: 'Integer', isCorrect: false }], explanation: 'Lists are mutable.', points: 10 },
  { technology: 'Python', category: 'Language', difficulty: 'easy', question: 'Which data type is immutable?', options: [{ text: 'List', isCorrect: false }, { text: 'Dictionary', isCorrect: false }, { text: 'Tuple', isCorrect: true }, { text: 'Set', isCorrect: false }], explanation: 'Tuples are immutable.', points: 10 },
  { technology: 'Python', category: 'Language', difficulty: 'easy', question: 'What does len() do?', options: [{ text: 'Adds values', isCorrect: false }, { text: 'Returns length', isCorrect: true }, { text: 'Converts type', isCorrect: false }, { text: 'Sorts list', isCorrect: false }], explanation: 'Returns length.', points: 10 },
  { technology: 'Python', category: 'Language', difficulty: 'medium', question: 'Which keyword handles exceptions?', options: [{ text: 'catch', isCorrect: false }, { text: 'try-except', isCorrect: true }, { text: 'error', isCorrect: false }, { text: 'handle', isCorrect: false }], explanation: 'Try-except block.', points: 15 },
  { technology: 'Python', category: 'Language', difficulty: 'medium', question: 'What is a lambda function?', options: [{ text: 'Named function', isCorrect: false }, { text: 'Anonymous function', isCorrect: true }, { text: 'Loop', isCorrect: false }, { text: 'Class', isCorrect: false }], explanation: 'Anonymous lambda.', points: 15 },
  { technology: 'Python', category: 'Language', difficulty: 'easy', question: 'Which loop is used for iteration?', options: [{ text: 'loop', isCorrect: false }, { text: 'for', isCorrect: true }, { text: 'iterate', isCorrect: false }, { text: 'each', isCorrect: false }], explanation: 'For loop.', points: 10 },
  { technology: 'Python', category: 'Language', difficulty: 'easy', question: 'What does pip do?', options: [{ text: 'Executes code', isCorrect: false }, { text: 'Installs packages', isCorrect: true }, { text: 'Debugs code', isCorrect: false }, { text: 'Compiles', isCorrect: false }], explanation: 'Package installer.', points: 10 },
  { technology: 'Python', category: 'Language', difficulty: 'easy', question: 'File extension of Python?', options: [{ text: '.java', isCorrect: false }, { text: '.py', isCorrect: true }, { text: '.js', isCorrect: false }, { text: '.exe', isCorrect: false }], explanation: '.py extension.', points: 10 },
  { technology: 'Python', category: 'Language', difficulty: 'medium', question: 'Which keyword defines a class?', options: [{ text: 'object', isCorrect: false }, { text: 'class', isCorrect: true }, { text: 'struct', isCorrect: false }, { text: 'define', isCorrect: false }], explanation: 'class keyword.', points: 15 },
  { technology: 'Python', category: 'Language', difficulty: 'medium', question: 'What is __init__?', options: [{ text: 'Destructor', isCorrect: false }, { text: 'Constructor', isCorrect: true }, { text: 'Method', isCorrect: false }, { text: 'Operator', isCorrect: false }], explanation: 'Constructor method.', points: 15 },
  { technology: 'Python', category: 'Language', difficulty: 'medium', question: 'What does yield do?', options: [{ text: 'Return value', isCorrect: false }, { text: 'Creates generator', isCorrect: true }, { text: 'Loop', isCorrect: false }, { text: 'Break', isCorrect: false }], explanation: 'Generator yield.', points: 15 },
  { technology: 'Python', category: 'Language', difficulty: 'hard', question: 'What is GIL?', options: [{ text: 'Global Index Lock', isCorrect: false }, { text: 'Global Interpreter Lock', isCorrect: true }, { text: 'General Input Loop', isCorrect: false }, { text: 'Graph Interface Layer', isCorrect: false }], explanation: 'Global Interpreter Lock.', points: 20 },
  { technology: 'Python', category: 'Language', difficulty: 'medium', question: 'List comprehension is used for?', options: [{ text: 'Sorting', isCorrect: false }, { text: 'Concise looping', isCorrect: true }, { text: 'Printing', isCorrect: false }, { text: 'Memory', isCorrect: false }], explanation: 'Concise collection handling.', points: 15 },
  { technology: 'Python', category: 'Language', difficulty: 'hard', question: 'What does async enable?', options: [{ text: 'Parallel execution', isCorrect: false }, { text: 'Asynchronous programming', isCorrect: true }, { text: 'Compilation', isCorrect: false }, { text: 'Sorting', isCorrect: false }], explanation: 'Asynchronous programming.', points: 20 },
  { technology: 'Python', category: 'Language', difficulty: 'medium', question: 'Which library is used for arrays?', options: [{ text: 'Pandas', isCorrect: false }, { text: 'NumPy', isCorrect: true }, { text: 'Matplotlib', isCorrect: false }, { text: 'SciPy', isCorrect: false }], explanation: 'NumPy array support.', points: 15 },
  { technology: 'Python', category: 'Language', difficulty: 'medium', question: 'Which library is used for data analysis?', options: [{ text: 'NumPy', isCorrect: false }, { text: 'Pandas', isCorrect: true }, { text: 'Flask', isCorrect: false }, { text: 'Django', isCorrect: false }], explanation: 'Pandas analysis.', points: 15 },
  { technology: 'Python', category: 'Language', difficulty: 'medium', question: 'Decorators use which symbol?', options: [{ text: '#', isCorrect: false }, { text: '@', isCorrect: true }, { text: '$', isCorrect: false }, { text: '&', isCorrect: false }], explanation: '@ symbol.', points: 15 },
  { technology: 'Python', category: 'Language', difficulty: 'medium', question: 'Python supports OOP?', options: [{ text: 'No', isCorrect: false }, { text: 'Yes', isCorrect: true }, { text: 'Limited', isCorrect: false }, { text: 'Only classes', isCorrect: false }], explanation: 'Full OOP support.', points: 15 },

  // --- JAVA (20) ---
  { technology: 'Java', category: 'Language', difficulty: 'easy', question: 'What does JVM stand for?', options: [{ text: 'Java Variable Machine', isCorrect: false }, { text: 'Java Virtual Machine', isCorrect: true }, { text: 'Java Verified Machine', isCorrect: false }, { text: 'Java Visual Model', isCorrect: false }], explanation: 'Java Virtual Machine.', points: 10 },
  { technology: 'Java', category: 'Language', difficulty: 'medium', question: 'Which component includes compiler and tools?', options: [{ text: 'JRE', isCorrect: false }, { text: 'JDK', isCorrect: true }, { text: 'JVM', isCorrect: false }, { text: 'JIT', isCorrect: false }], explanation: 'JDK includes developer tools.', points: 15 },
  { technology: 'Java', category: 'Language', difficulty: 'easy', question: 'Which keyword is used to define a class?', options: [{ text: 'struct', isCorrect: false }, { text: 'class', isCorrect: true }, { text: 'define', isCorrect: false }, { text: 'object', isCorrect: false }], explanation: 'class keyword.', points: 10 },
  { technology: 'Java', category: 'Language', difficulty: 'easy', question: 'What is the entry point of a Java program?', options: [{ text: 'start()', isCorrect: false }, { text: 'init()', isCorrect: false }, { text: 'main()', isCorrect: true }, { text: 'run()', isCorrect: false }], explanation: 'main() method.', points: 10 },
  { technology: 'Java', category: 'Language', difficulty: 'medium', question: 'Which OOP concept allows multiple methods with same name?', options: [{ text: 'Inheritance', isCorrect: false }, { text: 'Encapsulation', isCorrect: false }, { text: 'Polymorphism', isCorrect: true }, { text: 'Abstraction', isCorrect: false }], explanation: 'Polymorphism.', points: 15 },
  { technology: 'Java', category: 'Language', difficulty: 'medium', question: 'Which keyword is used to inherit a class?', options: [{ text: 'implement', isCorrect: false }, { text: 'extends', isCorrect: true }, { text: 'inherit', isCorrect: false }, { text: 'super', isCorrect: false }], explanation: 'extends keyword.', points: 15 },
  { technology: 'Java', category: 'Language', difficulty: 'easy', question: 'Which keyword is used to define constant?', options: [{ text: 'const', isCorrect: false }, { text: 'final', isCorrect: true }, { text: 'static', isCorrect: false }, { text: 'immutable', isCorrect: false }], explanation: 'final keyword.', points: 10 },
  { technology: 'Java', category: 'Language', difficulty: 'medium', question: 'Which collection does not allow duplicates?', options: [{ text: 'List', isCorrect: false }, { text: 'Set', isCorrect: true }, { text: 'Map', isCorrect: false }, { text: 'Array', isCorrect: false }], explanation: 'Set collection.', points: 15 },
  { technology: 'Java', category: 'Language', difficulty: 'easy', question: 'Which package contains core classes?', options: [{ text: 'java.io', isCorrect: false }, { text: 'java.util', isCorrect: false }, { text: 'java.lang', isCorrect: true }, { text: 'java.net', isCorrect: false }], explanation: 'java.lang package.', points: 10 },
  { technology: 'Java', category: 'Language', difficulty: 'medium', question: 'Which keyword is used for exception handling?', options: [{ text: 'try-catch', isCorrect: true }, { text: 'error', isCorrect: false }, { text: 'handle', isCorrect: false }, { text: 'catch-all', isCorrect: false }], explanation: 'Try-catch block.', points: 15 },
  { technology: 'Java', category: 'Language', difficulty: 'medium', question: 'What is method overloading?', options: [{ text: 'Same name different parameters', isCorrect: true }, { text: 'Same method repeated', isCorrect: false }, { text: 'Different name same logic', isCorrect: false }, { text: 'Multiple classes', isCorrect: false }], explanation: 'Overloading same name.', points: 15 },
  { technology: 'Java', category: 'Language', difficulty: 'medium', question: 'Which interface is used for threads?', options: [{ text: 'Runnable', isCorrect: true }, { text: 'Threadable', isCorrect: false }, { text: 'Executor', isCorrect: false }, { text: 'Callable', isCorrect: false }], explanation: 'Runnable interface.', points: 15 },
  { technology: 'Java', category: 'Language', difficulty: 'medium', question: 'Which keyword refers to parent class?', options: [{ text: 'parent', isCorrect: false }, { text: 'super', isCorrect: true }, { text: 'base', isCorrect: false }, { text: 'this', isCorrect: false }], explanation: 'super keyword.', points: 15 },
  { technology: 'Java', category: 'Language', difficulty: 'medium', question: 'What is encapsulation?', options: [{ text: 'Data hiding', isCorrect: true }, { text: 'Inheritance', isCorrect: false }, { text: 'Polymorphism', isCorrect: false }, { text: 'Compilation', isCorrect: false }], explanation: 'Data encapsulation.', points: 15 },
  { technology: 'Java', category: 'Language', difficulty: 'medium', question: 'Which loop executes at least once?', options: [{ text: 'for', isCorrect: false }, { text: 'while', isCorrect: false }, { text: 'do-while', isCorrect: true }, { text: 'foreach', isCorrect: false }], explanation: 'Do-while loop.', points: 15 },
  { technology: 'Java', category: 'Language', difficulty: 'medium', question: 'Which keyword is used for interface implementation?', options: [{ text: 'extends', isCorrect: false }, { text: 'implements', isCorrect: true }, { text: 'inherit', isCorrect: false }, { text: 'use', isCorrect: false }], explanation: 'implements keyword.', points: 15 },
  { technology: 'Java', category: 'Language', difficulty: 'medium', question: 'What is garbage collection?', options: [{ text: 'Memory allocation', isCorrect: false }, { text: 'Memory deallocation automatically', isCorrect: true }, { text: 'Compilation', isCorrect: false }, { text: 'Execution', isCorrect: false }], explanation: 'Automated memory cleanup.', points: 15 },
  { technology: 'Java', category: 'Language', difficulty: 'medium', question: 'Which feature supports runtime polymorphism?', options: [{ text: 'Overloading', isCorrect: false }, { text: 'Overriding', isCorrect: true }, { text: 'Inheritance', isCorrect: false }, { text: 'Abstraction', isCorrect: false }], explanation: 'Runtime overriding.', points: 15 },
  { technology: 'Java', category: 'Language', difficulty: 'easy', question: 'Which type stores true/false?', options: [{ text: 'int', isCorrect: false }, { text: 'boolean', isCorrect: true }, { text: 'char', isCorrect: false }, { text: 'float', isCorrect: false }], explanation: 'Boolean type.', points: 10 },
  { technology: 'Java', category: 'Language', difficulty: 'medium', question: 'Which operator compares values?', options: [{ text: '=', isCorrect: false }, { text: '==', isCorrect: true }, { text: '!=', isCorrect: false }, { text: '===', isCorrect: false }], explanation: 'Equals operator.', points: 15 }
];

async function seed() {
  await connectDB();
  await Question.insertMany(allRemainingQuestions);
  console.log(`Seed successful! Inserted ${allRemainingQuestions.length} remaining questions (CSS, Next.js, Python, Java).`);
  process.exit();
}
seed();
